package currency

import "github.com/leekchan/accounting"

const (
	AUD = "AUD"
	CAD = "CAD"
	CHF = "CHF"
	CNY = "CNY"
	DKK = "DKK"
	EUR = "EUR"
	GBP = "GBP"
	JPY = "JPY"
	KRW = "KRW"
	MXN = "MXN"
	NOK = "NOK"
	NZD = "NZD"
	PLN = "PLN"
	SEK = "SEK"
	SGD = "SGD"
	TWD = "TWD"
	USD = "USD"
)

// LocaleInfo was derived from accounting.LocaleInfo, with adjustments:
// AUD: ThouSep " " => ","
// CAD: ComSymbol "CA$" => "$"
// DKK: ComSymbol "kr." => " kr" ; Pre true => false
// NOK: ComSymbol "kr" => " kr" ; ThouSep "." => " " ; Pre true => false
// PLN: ComSymbol "zł" => " zł"
// SEK: ComSymbol "kr" => " kr"
//
// NOTE:
// 1. The formatting of European currencies is locale and context dependent.
// 2. Technically, TWD has decimal subunits, but they are not used in practice.
var LocaleInfo = map[string]accounting.Locale{
	"AED": {Name: "UAE Dirham", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "Dhs.", Pre: true},
	"AFA": {Name: "Afghani", FractionLength: 0, SpaceSep: "060B", UTFSymbol: "&#x060B;", ComSymbol: "؋", Pre: true},
	"ALL": {Name: "Lek", FractionLength: 2, ComSymbol: "Lek ", Pre: true},
	"AMD": {Name: "Armenian Dram", FractionLength: 2, ThouSep: ",", DecSep: ".", ComSymbol: "֏", Pre: false},
	"ANG": {Name: "Antillian Guilder", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", UTFSymbol: "0192", HTMLSymbol: "&#x0192;", ComSymbol: "ƒ", Pre: true},
	"AOA": {Name: "New Kwanza", FractionLength: 0, ComSymbol: "Kz ", Pre: true},
	"ARS": {Name: "Argentine Peso", FractionLength: 2, ThouSep: ".", DecSep: ",", UTFSymbol: "20B1", HTMLSymbol: "&#x20B1;", ComSymbol: "$", Pre: true},
	"ATS": {Name: "Schilling", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", ComSymbol: "öS ", Pre: true},
	"AUD": {Name: "Australian Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"AWG": {Name: "Aruban Guilder", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "0192", HTMLSymbol: "&#x0192;", ComSymbol: "ƒ", Pre: true},
	"AZN": {Name: "Azerbaijanian Manat", FractionLength: 2, ComSymbol: "₼", Pre: true},
	"BAM": {Name: "Convertible Marks", FractionLength: 2, ThouSep: ",", DecSep: ".", ComSymbol: "KM ", Pre: false},
	"BBD": {Name: "Barbados Dollar", FractionLength: 2, UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "Bds$ ", Pre: true},
	"BDT": {Name: "Taka", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "Tk ", Pre: true},
	"BEF": {Name: "Belgian Franc", FractionLength: 0, ThouSep: ".", SpaceSep: " ", UTFSymbol: "20A3", HTMLSymbol: "&#x20A3;", ComSymbol: "BEF ", Pre: true},
	"BGN": {Name: "Lev", FractionLength: 2, ThouSep: " ", DecSep: ",", SpaceSep: " ", ComSymbol: "лв", Pre: false},
	"BHD": {Name: "Bahraini Dinar", FractionLength: 3, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "د.ب", Pre: true},
	"BIF": {Name: "Burundi Franc", FractionLength: 0, ComSymbol: "FBu ", Pre: true},
	"BMD": {Name: "Bermudian Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"BND": {Name: "Brunei Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"BOB": {Name: "Bolivian Boliviano", FractionLength: 2, ThouSep: ",", DecSep: ".", ComSymbol: "$b", Pre: true},
	"BRL": {Name: "Brazilian Real", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", UTFSymbol: "0052 0024", HTMLSymbol: "R$", ComSymbol: "R$", Pre: true},
	"BSD": {Name: "Bahamian Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"BTN": {Name: "Bhutan Ngultrum", FractionLength: 2, ComSymbol: "BTN ", Pre: true},
	"BWP": {Name: "Pula", FractionLength: 2, ThouSep: ",", DecSep: ".", ComSymbol: "P", Pre: true},
	"BYR": {Name: "Belarussian Ruble", FractionLength: 0, ComSymbol: "p. ", Pre: true},
	"BZD": {Name: "Belize Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"CAD": {Name: "Canadian Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"CDF": {Name: "Franc Congolais", FractionLength: 2, ComSymbol: "FC ", Pre: true},
	"CHF": {Name: "Swiss Franc", FractionLength: 2, ThouSep: "'", DecSep: ".", SpaceSep: " ", ComSymbol: "CHF ", Pre: true},
	"CLP": {Name: "Chilean Peso", FractionLength: 0, ThouSep: ".", UTFSymbol: "20B1", HTMLSymbol: "&#x20B1;", ComSymbol: "$", Pre: true},
	"CNY": {Name: "Yuan Renminbi", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "5713", HTMLSymbol: "&#x5713;", ComSymbol: "¥", Pre: true},
	"COP": {Name: "Colombian Peso", FractionLength: 2, ThouSep: ".", DecSep: ",", UTFSymbol: "20B1", HTMLSymbol: "&#x20B1;", ComSymbol: "$", Pre: true},
	"CRC": {Name: "Costa Rican Colon", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", UTFSymbol: "20A1", HTMLSymbol: "&#x20A1;", ComSymbol: "₡", Pre: true},
	"CUP": {Name: "Cuban Peso", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "20B1", HTMLSymbol: "&#x20B1;", ComSymbol: "$", Pre: true},
	"CVE": {Name: "Cape Verde Escudo", FractionLength: 0, ComSymbol: "$", Pre: true},
	"CYP": {Name: "Cyprus Pound", FractionLength: 2, ThouSep: ".", DecSep: ",", UTFSymbol: "00A3", HTMLSymbol: "&#x00A3;", ComSymbol: "£", Pre: true},
	"CZK": {Name: "Czech Koruna", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", ComSymbol: "Kč", Pre: false},
	"DEM": {Name: "Deutsche Mark", FractionLength: 2, ThouSep: ".", DecSep: ",", ComSymbol: "DM ", Pre: false},
	"DJF": {Name: "Djibouti Franc", FractionLength: 0, ComSymbol: "DJF ", Pre: true},
	"DKK": {Name: "Danish Krone", FractionLength: 2, ThouSep: ".", DecSep: ",", ComSymbol: " kr", Pre: false},
	"DOP": {Name: "Dominican Peso", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "20B1", HTMLSymbol: "&#x20B1;", ComSymbol: "$", Pre: true},
	"DZD": {Name: "Algerian Dinar", FractionLength: 2, ComSymbol: "DA", Pre: true},
	"ECS": {Name: "Sucre", FractionLength: 0, ComSymbol: "S.", Pre: true},
	"EEK": {Name: "Kroon", FractionLength: 2, ThouSep: " ", DecSep: ",", SpaceSep: " ", ComSymbol: "kr", Pre: false},
	"EGP": {Name: "Egyptian Pound", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "00A3", HTMLSymbol: "&#x00A3;", ComSymbol: "£", Pre: true},
	"ERN": {Name: "Nakfa", FractionLength: 0, ComSymbol: "NKf ", Pre: true},
	"ESP": {Name: "Spanish Peseta", FractionLength: 0, ThouSep: ".", SpaceSep: " ", UTFSymbol: "20A7", HTMLSymbol: "&#x20A7;", ComSymbol: "Ptas", Pre: false},
	"ETB": {Name: "Ethiopian Birr", FractionLength: 0, ComSymbol: "BR", Pre: true},
	"EUR": {Name: "Euro", FractionLength: 2, ThouSep: ".", DecSep: ",", UTFSymbol: "20AC", HTMLSymbol: "&#x20AC;", ComSymbol: "€", Pre: true},
	"FIM": {Name: "Markka", FractionLength: 2, ThouSep: " ", DecSep: ",", SpaceSep: " ", ComSymbol: "mk", Pre: false},
	"FJD": {Name: "Fiji Dollar", FractionLength: 0, UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "FJ$", Pre: true},
	"FKP": {Name: "Pound", FractionLength: 0, UTFSymbol: "00A3", HTMLSymbol: "&#x00A3;", ComSymbol: "£", Pre: true},
	"FRF": {Name: "French Franc", FractionLength: 2, ThouSep: " ", DecSep: ",", SpaceSep: " ", UTFSymbol: "20A3", HTMLSymbol: "&#x20A3;", ComSymbol: "Fr", Pre: false},
	"GBP": {Name: "Pound Sterling", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "00A3", HTMLSymbol: "&#x00A3;", ComSymbol: "£", Pre: true},
	"GEL": {Name: "Lari", FractionLength: 0, ComSymbol: "GEL ", Pre: true},
	"GHS": {Name: "Cedi", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "20B5", HTMLSymbol: "&#x20B5;", ComSymbol: "₵", Pre: true},
	"GIP": {Name: "Gibraltar Pound", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "00A3", HTMLSymbol: "&#x00A3;", ComSymbol: "£", Pre: true},
	"GMD": {Name: "Dalasi", FractionLength: 0, ComSymbol: "GMD ", Pre: true},
	"GNF": {Name: "Guinea Franc", FractionLength: 0, ComSymbol: "FG", Pre: true},
	"GRD": {Name: "Drachma", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", UTFSymbol: "20AF", HTMLSymbol: "&#x20AF;", ComSymbol: "GRD ", Pre: false},
	"GTQ": {Name: "Quetzal", FractionLength: 2, ThouSep: ",", DecSep: ".", ComSymbol: "Q.", Pre: true},
	"GWP": {Name: "Guinea-Bissau Peso", FractionLength: 0, ComSymbol: "GWP ", Pre: true},
	"GYD": {Name: "Guyana Dollar", FractionLength: 0, UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"HKD": {Name: "Hong Kong Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "HK$", Pre: true},
	"HNL": {Name: "Lempira", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "L", Pre: true},
	"HRK": {Name: "Kuna", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", ComSymbol: "kn", Pre: false},
	"HTG": {Name: "Gourde", FractionLength: 0, ComSymbol: "G", Pre: true},
	"HUF": {Name: "Forint", FractionLength: 0, ThouSep: ".", SpaceSep: " ", ComSymbol: "Ft", Pre: false},
	"IDR": {Name: "Rupiah", FractionLength: 0, ThouSep: ".", DecSep: ",", ComSymbol: "Rp.", Pre: true},
	"IEP": {Name: "Irish Pound", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "00A3", HTMLSymbol: "&#x00A3;", ComSymbol: "£", Pre: true},
	"ILS": {Name: "New Israeli Sheqel", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "20AA", HTMLSymbol: "&#x20AA;", ComSymbol: "₪", Pre: false},
	"INR": {Name: "Indian Rupee", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "20A8", HTMLSymbol: "&#x20A8;", ComSymbol: "₹", Pre: true},
	"IQD": {Name: "Iraqi Dinar", FractionLength: 3, ComSymbol: "د.ع", Pre: true},
	"IRR": {Name: "Iranian Rial", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "FDFC", HTMLSymbol: "&#xFDFC;", ComSymbol: "﷼", Pre: true},
	"ISK": {Name: "Iceland Krona", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", ComSymbol: "kr", Pre: false},
	"ITL": {Name: "Italian Lira", FractionLength: 0, ThouSep: ".", SpaceSep: " ", UTFSymbol: "20A4", HTMLSymbol: "&#x20A4;", ComSymbol: "L.", Pre: true},
	"JMD": {Name: "Jamaican Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"JOD": {Name: "Jordanian Dinar", FractionLength: 3, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "JD", Pre: true},
	"JPY": {Name: "Yen", FractionLength: 0, ThouSep: ",", UTFSymbol: "00A5", HTMLSymbol: "&#x00A5;", ComSymbol: "¥", Pre: true},
	"KES": {Name: "Kenyan Shilling", FractionLength: 2, ThouSep: ",", DecSep: ".", ComSymbol: "Ksh", Pre: true},
	"KGS": {Name: "Som", FractionLength: 0, ComSymbol: "лв", Pre: true},
	"KHR": {Name: "Riel", FractionLength: 2, UTFSymbol: "17DB", HTMLSymbol: "&#x17DB;", ComSymbol: "៛", Pre: true},
	"KMF": {Name: "Comoro Franc", FractionLength: 0, ComSymbol: "KMF ", Pre: true},
	"KPW": {Name: "North Korean Won", FractionLength: 0, UTFSymbol: "20A9", HTMLSymbol: "&#x20A9;", ComSymbol: "₩", Pre: true},
	"KRW": {Name: "Won", FractionLength: 0, ThouSep: ",", UTFSymbol: "20A9", HTMLSymbol: "&#x20A9;", ComSymbol: "₩", Pre: true},
	"KWD": {Name: "Kuwaiti Dinar", FractionLength: 3, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "ك", Pre: true},
	"KYD": {Name: "Cayman Islands Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"KZT": {Name: "Tenge", FractionLength: 0, ComSymbol: "₸", Pre: true},
	"LAK": {Name: "Kip", FractionLength: 0, UTFSymbol: "20AD", HTMLSymbol: "&#x20AD;", ComSymbol: "₭", Pre: true},
	"LBP": {Name: "Lebanese Pound", FractionLength: 0, ThouSep: " ", UTFSymbol: "00A3", HTMLSymbol: "&#x00A3;", ComSymbol: "ل.ل", Pre: false},
	"LKR": {Name: "Sri Lanka Rupee", FractionLength: 0, UTFSymbol: "0BF9", HTMLSymbol: "&#x0BF9;", ComSymbol: "₨", Pre: true},
	"LRD": {Name: "Liberian Dollar", FractionLength: 0, UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"LSL": {Name: "Lesotho Maloti", FractionLength: 0, ComSymbol: "LSL ", Pre: true},
	"LTL": {Name: "Lithuanian Litas", FractionLength: 2, ThouSep: " ", DecSep: ",", SpaceSep: " ", ComSymbol: "Lt", Pre: false},
	"LUF": {Name: "Luxembourg Franc", FractionLength: 0, ThouSep: "'", SpaceSep: " ", UTFSymbol: "20A3", HTMLSymbol: "&#x20A3;", ComSymbol: "F", Pre: false},
	"LVL": {Name: "Latvian Lats", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "Ls", Pre: true},
	"LYD": {Name: "Libyan Dinar", FractionLength: 0, ComSymbol: "LD ", Pre: true},
	"MAD": {Name: "Moroccan Dirham", FractionLength: 0, ComSymbol: "MAD ", Pre: true},
	"MDL": {Name: "Moldovan Leu", FractionLength: 0, ComSymbol: "MDL ", Pre: true},
	"MGF": {Name: "Malagasy Franc", FractionLength: 0, ComSymbol: "MF", Pre: true},
	"MKD": {Name: "Denar", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "ден", Pre: false},
	"MMK": {Name: "Kyat", FractionLength: 0, ComSymbol: "K", Pre: true},
	"MNT": {Name: "Tugrik", FractionLength: 0, UTFSymbol: "20AE", HTMLSymbol: "&#x20AE;", ComSymbol: "₮", Pre: true},
	"MOP": {Name: "Pataca", FractionLength: 0, ComSymbol: "MOP$", Pre: true},
	"MRO": {Name: "Ouguiya", FractionLength: 0, ComSymbol: "MRO ", Pre: true},
	"MTL": {Name: "Maltese Lira", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "20A4", HTMLSymbol: "&#x20A4;", ComSymbol: "Lm", Pre: true},
	"MUR": {Name: "Mauritius Rupee", FractionLength: 0, ThouSep: ",", UTFSymbol: "20A8", HTMLSymbol: "&#x20A8;", ComSymbol: "Rs", Pre: true},
	"MVR": {Name: "Rufiyaa", FractionLength: 0, ComSymbol: "MVR ", Pre: true},
	"MWK": {Name: "Kwacha", FractionLength: 2, ThouSep: ",", DecSep: ".", ComSymbol: "MK ", Pre: true},
	"MXN": {Name: "Mexican Peso", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"MYR": {Name: "Malaysian Ringgit", FractionLength: 2, ThouSep: ",", DecSep: ".", ComSymbol: "RM", Pre: true},
	"MZN": {Name: "Metical", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", ComSymbol: "Mt", Pre: false},
	"NAD": {Name: "Namibian Dollar", FractionLength: 0, UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"NGN": {Name: "Naira", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: ".", UTFSymbol: "20A6", HTMLSymbol: "&#x20A6;", ComSymbol: "₦", Pre: true},
	"NIO": {Name: "Cordoba Oro", FractionLength: 0, ComSymbol: "C$", Pre: true},
	"NLG": {Name: "Netherlands Guilder", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", UTFSymbol: "0192", HTMLSymbol: "&#x0192;", ComSymbol: "ƒ", Pre: true},
	"NOK": {Name: "Norwegian Krone", FractionLength: 2, ThouSep: " ", DecSep: ",", SpaceSep: " ", UTFSymbol: "kr", HTMLSymbol: "kr", ComSymbol: " kr", Pre: false},
	"NPR": {Name: "Nepalese Rupee", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "20A8", HTMLSymbol: "&#x20A8;", ComSymbol: "Rs.", Pre: true},
	"NZD": {Name: "New Zealand Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"OMR": {Name: "Rial Omani", FractionLength: 3, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "FDFC", HTMLSymbol: "&#xFDFC;", ComSymbol: "RO", Pre: true},
	"PAB": {Name: "Balboa", FractionLength: 0, ComSymbol: "B/.", Pre: true},
	"PEN": {Name: "Nuevo Sol", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "S/.", HTMLSymbol: "S/.", ComSymbol: "S/.", Pre: true},
	"PGK": {Name: "Kina", FractionLength: 0, ComSymbol: "K", Pre: true},
	"PHP": {Name: "Philippine Peso", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "20B1", HTMLSymbol: "&#x20B1;", ComSymbol: "₱", Pre: true},
	"PKR": {Name: "Pakistan Rupee", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "20A8", HTMLSymbol: "&#x20A8;", ComSymbol: "Rs", Pre: true},
	"PLN": {Name: "Zloty", FractionLength: 2, ThouSep: " ", DecSep: ",", SpaceSep: " ", ComSymbol: " zł", Pre: false},
	"PTE": {Name: "Portuguese Escudo", FractionLength: 0, ThouSep: ".", SpaceSep: " ", ComSymbol: " $", Pre: false},
	"PYG": {Name: "Guarani", FractionLength: 0, UTFSymbol: "20B2", HTMLSymbol: "&#x20B2;", ComSymbol: "Gs", Pre: true},
	"QAR": {Name: "Qatari Rial", FractionLength: 0, UTFSymbol: "FDFC", HTMLSymbol: "&#xFDFC;", ComSymbol: "﷼ ", Pre: true},
	"RON": {Name: "Leu", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", ComSymbol: "lei", Pre: false},
	"RSD": {Name: "Serbian Dinar", FractionLength: 2, ComSymbol: "РСД", Pre: false},
	"RUB": {Name: "Russian Ruble", FractionLength: 2, ThouSep: ".", DecSep: ",", UTFSymbol: "0440 0443 0431", HTMLSymbol: "&#x0440;&#x0443;&#x0431;", ComSymbol: "₽", Pre: true},
	"RWF": {Name: "Rwanda Franc", FractionLength: 0, ComSymbol: "RWF ", Pre: true},
	"SAC": {Name: "S. African Rand Commerc.", FractionLength: 0, ComSymbol: "SAC ", Pre: true},
	"SAR": {Name: "Saudi Riyal", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "FDFC", HTMLSymbol: "&#xFDFC;", ComSymbol: "﷼", Pre: true},
	"SBD": {Name: "Solomon Islands Dollar", FractionLength: 0, UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"SCR": {Name: "Seychelles Rupee", FractionLength: 0, UTFSymbol: "20A8", HTMLSymbol: "&#x20A8;", ComSymbol: "₨", Pre: true},
	"SDG": {Name: "Sudanese Dinar", FractionLength: 0, ComSymbol: "LSd", Pre: true},
	"SDP": {Name: "Sudanese Pound", FractionLength: 0, ComSymbol: "SDP ", Pre: true},
	"SEK": {Name: "Swedish Krona", FractionLength: 2, ThouSep: " ", DecSep: ",", SpaceSep: " ", ComSymbol: " kr", Pre: false},
	"SGD": {Name: "Singapore Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"SHP": {Name: "St Helena Pound", FractionLength: 0, UTFSymbol: "00A3", HTMLSymbol: "&#x00A3;", ComSymbol: "£", Pre: true},
	"SIT": {Name: "Tolar", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", ComSymbol: "SIT ", Pre: false},
	"SKK": {Name: "Slovak Koruna", FractionLength: 2, ThouSep: " ", DecSep: ",", SpaceSep: " ", ComSymbol: "Sk", Pre: false},
	"SLL": {Name: "Leone", FractionLength: 0, ComSymbol: "Le ", Pre: true},
	"SOS": {Name: "Somali Shilling", FractionLength: 0, ComSymbol: "S", Pre: true},
	"SRG": {Name: "Surinam Guilder", FractionLength: 0, ComSymbol: "SRG ", Pre: true},
	"STD": {Name: "Dobra", FractionLength: 0, ComSymbol: "DB", Pre: true},
	"SVC": {Name: "El Salvador Colon", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "20A1", HTMLSymbol: "&#x20A1;", ComSymbol: "¢", Pre: true},
	"SYP": {Name: "Syrian Pound", FractionLength: 0, UTFSymbol: "00A3", HTMLSymbol: "&#x00A3;", ComSymbol: "£", Pre: true},
	"SZL": {Name: "Lilangeni", FractionLength: 2, DecSep: ".", ComSymbol: "E", Pre: true},
	"THB": {Name: "Baht", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", UTFSymbol: "0E3F", HTMLSymbol: "&#x0E3F;", ComSymbol: "Bt", Pre: false},
	"TJR": {Name: "Tajik Ruble", FractionLength: 0, ComSymbol: "TJR ", Pre: true},
	"TJS": {Name: "Somoni", FractionLength: 0, ComSymbol: "TJS ", Pre: true},
	"TMM": {Name: "Manat", FractionLength: 0, ComSymbol: "T", Pre: true},
	"TND": {Name: "Tunisian Dinar", FractionLength: 3, ComSymbol: "TND ", Pre: true},
	"TOP": {Name: "Pa'anga", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "$", Pre: true},
	"TPE": {Name: "Timor Escudo", FractionLength: 0, ComSymbol: "TPE ", Pre: true},
	"TRY": {Name: "Turkish Lira", FractionLength: 0, ThouSep: ",", UTFSymbol: "20A4", HTMLSymbol: "&#x20A4;", ComSymbol: "TL", Pre: false},
	"TTD": {Name: "Trinidad and Tobago Dollar", FractionLength: 0, UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "TT$", Pre: true},
	"TWD": {Name: "New Taiwan Dollar", FractionLength: 0, UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "NT$", Pre: true},
	"TZS": {Name: "Tanzanian Shilling", FractionLength: 2, ThouSep: ",", DecSep: ".", SpaceSep: " ", ComSymbol: "TZs", Pre: false},
	"UAH": {Name: "Hryvnia", FractionLength: 2, ThouSep: " ", DecSep: ",", UTFSymbol: "20B4", HTMLSymbol: "&#x20B4", ComSymbol: "UAH ", Pre: false},
	"UGX": {Name: "Uganda Shilling", FractionLength: 0, ComSymbol: "UGX", Pre: true},
	"USD": {Name: "US Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"UYU": {Name: "Peso Uruguayo", FractionLength: 2, ThouSep: ".", DecSep: ",", UTFSymbol: "20B1", HTMLSymbol: "&#x20B1;", ComSymbol: "$", Pre: true},
	"UZS": {Name: "Uzbekistan Sum", FractionLength: 0, ComSymbol: "лв", Pre: true},
	"VEF": {Name: "Bolivar", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", ComSymbol: "Bs.", Pre: true},
	"VND": {Name: "Dong", FractionLength: 2, ThouSep: ".", DecSep: ",", SpaceSep: " ", UTFSymbol: "20AB", HTMLSymbol: "&#x20AB;", ComSymbol: "₫", Pre: true},
	"VUV": {Name: "Vatu", FractionLength: 0, ThouSep: ",", ComSymbol: "VT", Pre: false},
	"WST": {Name: "Tala", FractionLength: 0, ComSymbol: "WST ", Pre: true},
	"XAF": {Name: "CFA Franc BEAC", FractionLength: 0, ComSymbol: "$", Pre: true},
	"XCD": {Name: "East Caribbean Dollar", FractionLength: 2, ThouSep: ",", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "$", Pre: true},
	"XOF": {Name: "CFA Franc BCEAO", FractionLength: 0, ComSymbol: "XOF ", Pre: true},
	"XPF": {Name: "CFP Franc", FractionLength: 0, ComSymbol: "XPF ", Pre: true},
	"YER": {Name: "Yemeni Rial", FractionLength: 0, UTFSymbol: "FDFC", HTMLSymbol: "&#xFDFC;", ComSymbol: "﷼ ", Pre: true},
	"YUN": {Name: "New Dinar", FractionLength: 0, ComSymbol: "YUN ", Pre: true},
	"ZAR": {Name: "Rand", FractionLength: 2, ThouSep: " ", DecSep: ".", SpaceSep: " ", UTFSymbol: "0052", HTMLSymbol: "&#x0052;", ComSymbol: "R", Pre: true},
	"ZMK": {Name: "Kwacha", FractionLength: 0, ComSymbol: "ZMK ", Pre: true},
	"ZRN": {Name: "New Zaire", FractionLength: 0, ComSymbol: "ZRN ", Pre: true},
	"ZWD": {Name: "Zimbabwe Dollar ", FractionLength: 2, ThouSep: " ", DecSep: ".", UTFSymbol: "0024", HTMLSymbol: "&#x0024;", ComSymbol: "Z$", Pre: true},
}
