version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 40
    errcheck:
      exclude-functions:
        - io.Copy
        - io.ReadAll
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - ifElseChain
        - hugeParam
  exclusions:
    paths:
      - vendor
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
      - text: '`.*\.(Close|Rollback|Commit|Quit|Disconnect|ClosePool)\`'
        linters:
          - errcheck

issues:
  max-issues-per-linter: 50
  max-same-issues: 5

run:
  timeout: 5m
