linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 20
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - ifElseChain
      - hugeParam
  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 50
  max-same-issues: 5

run:
  timeout: 5m
