BEGIN;

ALTER TABLE public.adventure_game_item
    ADD COLUMN IF NOT EXISTS can_be_used BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS damage INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS defense INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS heal_amount INT NOT NULL DEFAULT 0;

COMMIT;
