package mecha

import (
	"context"
	"fmt"

	"gitlab.com/alienspaces/playbymail/internal/record/game_record"
	"gitlab.com/alienspaces/playbymail/internal/record/mecha_record"
)

// CreateTurnSheets creates all turn sheet records for the current turn of a mecha instance.
func (p *Mecha) CreateTurnSheets(ctx context.Context, gameInstanceRec *game_record.GameInstance) ([]*game_record.GameTurnSheet, error) {
	l := p.Logger.WithFunctionContext("Mecha/CreateTurnSheets")

	l.Info("creating mecha turn sheets for instance >%s< turn >%d<", gameInstanceRec.ID, gameInstanceRec.CurrentTurn)

	squadInstanceRecs, err := p.getSquadInstancesForGameInstance(ctx, gameInstanceRec)
	if err != nil {
		l.Error("failed to get squad instances for game instance >%s< error >%v<", gameInstanceRec.ID, err)
		return nil, err
	}

	l.Info("found >%d< squad instances for game instance >%s<", len(squadInstanceRecs), gameInstanceRec.ID)

	if len(squadInstanceRecs) == 0 {
		l.Info("no squad instances found for game instance >%s<", gameInstanceRec.ID)
		return nil, nil
	}

	var errs []error
	var createdTurnSheets []*game_record.GameTurnSheet
	for _, squadInstanceRec := range squadInstanceRecs {
		squadTurnSheets, err := p.createSquadTurnSheets(ctx, gameInstanceRec, squadInstanceRec)
		if err != nil {
			l.Warn("failed to create turn sheets for squad >%s< error >%v<", squadInstanceRec.ID, err)
			errs = append(errs, err)
			continue
		}
		createdTurnSheets = append(createdTurnSheets, squadTurnSheets...)
	}

	if len(errs) > 0 {
		return nil, fmt.Errorf("failed to create turn sheets for some squads: %v", errs)
	}

	return createdTurnSheets, nil
}

// createSquadTurnSheets creates all of the current game turn's turn sheets for a squad.
// Computer-opponent squads produce no turn sheets; their orders are generated by the
// decision engine during turn processing instead.
func (p *Mecha) createSquadTurnSheets(ctx context.Context, gameInstanceRec *game_record.GameInstance, squadInstance *mecha_record.MechaSquadInstance) ([]*game_record.GameTurnSheet, error) {
	l := p.Logger.WithFunctionContext("Mecha/createSquadTurnSheets")

	l.Debug("creating turn sheets for squad instance >%s< turn number >%d<", squadInstance.ID, gameInstanceRec.CurrentTurn)

	// Look up the parent squad to determine ownership type.
	squadRec, err := p.Domain.GetMechaSquadRec(squadInstance.MechaSquadID, nil)
	if err != nil {
		l.Warn("failed to look up parent squad >%s< for squad instance >%s< error >%v<", squadInstance.MechaSquadID, squadInstance.ID, err)
		return nil, err
	}
	if squadRec.SquadType == mecha_record.SquadTypeOpponent {
		l.Debug("skipping turn sheet creation for computer-opponent squad instance >%s<", squadInstance.ID)
		return nil, nil
	}

	var createdTurnSheets []*game_record.GameTurnSheet

	for turnSheetType := range p.Processors {
		// Join game turn sheets are handled through the subscription workflow, not turn processing.
		if turnSheetType == mecha_record.MechaTurnSheetTypeJoinGame {
			continue
		}

		turnSheetRec, err := p.createTurnSheet(ctx, gameInstanceRec, squadInstance, turnSheetType)
		if err != nil {
			l.Warn("failed to create turn sheet >%s< for squad instance >%s< error >%v<", turnSheetType, squadInstance.ID, err)
			return nil, err
		}

		if turnSheetRec == nil {
			l.Debug("no turn sheet generated for type >%s< squad instance ID >%s< — skipping", turnSheetType, squadInstance.ID)
			continue
		}

		l.Debug("created turn sheet >%s< for squad instance ID >%s< turn sheet type >%s< turn number >%d<", turnSheetRec.ID, squadInstance.ID, turnSheetType, gameInstanceRec.CurrentTurn)
		createdTurnSheets = append(createdTurnSheets, turnSheetRec)
	}

	return createdTurnSheets, nil
}

// createTurnSheet creates a single turn sheet for a squad instance.
func (p *Mecha) createTurnSheet(ctx context.Context, gameInstanceRec *game_record.GameInstance, squadInstance *mecha_record.MechaSquadInstance, turnSheetType string) (*game_record.GameTurnSheet, error) {
	l := p.Logger.WithFunctionContext("Mecha/createTurnSheet")

	l.Debug("creating turn sheet type >%s< for game instance ID >%s< squad instance ID >%s<", turnSheetType, gameInstanceRec.ID, squadInstance.ID)

	processor, exists := p.Processors[turnSheetType]
	if !exists {
		l.Warn("unsupported sheet type >%s< for squad instance >%s<", turnSheetType, squadInstance.ID)
		return nil, fmt.Errorf("unsupported sheet type: %s", turnSheetType)
	}

	return processor.CreateNextTurnSheet(ctx, gameInstanceRec, squadInstance)
}
