#!/usr/bin/env sh

# Connect to the database in a QA environment.
#
# 1) Identify a pod that has connectivity to the database; the API server is a good choice.
# $ kubectl get pods
# 2) Connect to the database through the pod
# $ ./tools/db-connect-qa qa-hyakutake-api-7469c44496-rkzjq

pod=$1
if [ -z "$pod" ]; then
    echo "usage: $0 <pod>"
    exit 1
fi

con='psql "$DATABASE_URL"'

kubectl exec -it "$pod" -- sh -c "$con"
