#!/usr/bin/env sh

# Exports all data from the specified table as SQL to a file

. "$(dirname "$0")"/environment || exit $?

if [ -z "$PROJECT_NAME" ]; then
    echo "PROJECT_NAME must be set"
    exit 1
fi

table_name=$1
if [ -z "$table_name" ]; then
    echo "$0 [table_name]"
    exit 0
fi

pg_dump \
    -d "$DATABASE_URL" \
    --column-inserts \
    --data-only \
    --table="$table_name" \
    --file="$table_name.sql"
