#!/bin/sh

# Local development only.
# Usage: ./tools/db-setup


if [ "${CI:-}" != "" ]; then
    echo "This script is not meant to be run in CI"
    exit 1
fi

# This is a convenience script to idempotently start the database with all prerequisite data to run any service.

SCRIPT_DIR=$(dirname "$0")

. "$SCRIPT_DIR/environment" || exit $?
. "$SCRIPT_DIR/db-start" || exit $?
. "$SCRIPT_DIR/db-migrate-up" || exit $?
. "$SCRIPT_DIR/db-load-test-reference-data" || exit $?
. "$SCRIPT_DIR/db-load-test-data" || exit $?
