#!/bin/sh

# Local development only.
# Usage: ./tools/db-setup

# This is a convenience script to idempotently start the database with all prerequisite data to run any service.

cp .env.develop .env

SCRIPT_DIR=$(dirname "$0")

. "$SCRIPT_DIR/db-start" || exit $?
. "$SCRIPT_DIR/db-migrate-up" || exit $?
. "$SCRIPT_DIR/db-load-test-reference-data" || exit $?
. "$SCRIPT_DIR/db-load-test-data" || exit $?
