#!/bin/sh

# Local development only.
# Usage: ./tools/db-setup


if [ "${CI:-}" != "" ]; then
    echo "This script is not meant to be run in CI"
    exit 1
fi

# This is a convenience script to idempotently start the database with all prerequisite data to run any service.

. ./tools/environment || exit $?
. ./tools/db-start || exit $?
. ./tools/db-migrate-up || exit $?
. ./tools/db-load-test-reference-data || exit $?
. ./tools/db-load-test-data || exit $?
