#!/bin/sh

# Local development only.
# Usage: ./tools/db-setup-test

if [ "${CI:-}" != "" ]; then
    echo "This script is not meant to be run in CI"
    exit 1
fi

# This is a convenience script to idempotently start the database with all prerequisite data to run tests.

. ./tools/environment || exit $?
. ./tools/db-start || exit $?
. ./tools/db-migrate-up || exit $?
. ./tools/db-load-seed-reference-data || exit $?
