#!/bin/sh

# Retry a command a number of times with an
# increasing wait time between each attempt.
retry_cmd() {
  n=1
  max=5
  delay=3
  delay_inc=3

  echo "=> Command $*"

  while true; do
    "$@" && break
    if [ "$n" -lt "$max" ]; then
      n=$((n+1))
      echo "=> Command failed. Trying again in $delay seconds. Attempt $n/$max:"
      sleep "$delay"
      delay=$((delay+delay_inc))
    else
      echo "=> Command failed after $n attempts, exiting.." >&2
      exit 1
    fi
  done
}
