#!/usr/bin/env sh

echo
echo "=> Test backend custom"
echo

# Save current directory
orig_dir=$(pwd)

cd backend || exit 1

echo "=> Test backend custom - Running tests"
TESTING=true go test -v -failfast $@ || exit $?

# Return to original directory
cd "$orig_dir" || exit 1
