#!/usr/bin/env sh

echo
echo "=> Test backend internal"
echo

# Save current directory
orig_dir=$(pwd)

cd backend || exit 1

echo "=> Test backend internal - Running tests"
go test -v -failfast ./internal/... || exit $?

# Return to original directory
cd "$orig_dir" || exit 1
