#!/usr/bin/env sh

# CI only.
# Usage: ./tools/test-ci

if [ -z "$CI" ]; then
    echo "This script is only meant to be run in CI"
    exit 1
fi

# This script is executed during the test CI stage to run backend tests.

. ./tools/db-migrate-up || exit $?

. ./tools/db-load-test-reference-data || exit $?

# test core
. ./tools/test-backend-core || exit $?

# test internal
. ./tools/test-backend-internal || exit $?
