#!/usr/bin/env sh

# Use this script to set up the environment and run all backend tests.

# Local development only.
# Usage: ./tools/test

# copy develop env

cp .env.develop .env

# environment
. ./tools/environment || exit $?

# setup test database
. ./tools/db-setup-test || exit $?

# test core
. ./tools/test-backend-core || exit $?

# test internal
. ./tools/test-backend-internal || exit $?

# stop test database
. ./tools/db-stop || exit $?
