#!/usr/bin/env sh

# CI only.
# Usage: ./tools/test-ci

if [ -z "$CI" ]; then
    echo "This script is only meant to be run in CI"
    exit 1
fi

# This script is executed during the test CI stage to run backend tests.

. "$(dirname "$0")"/db-migrate-up || exit $?

. "$(dirname "$0")"/db-load-test-reference-data || exit $?

# test core
. "$(dirname "$0")"/test-backend-core || exit $?

# test internal
. "$(dirname "$0")"/test-backend-internal || exit $?

